version: '3.8'

services:
  web:
    build: .
    container_name: my_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - '80:80'
    environment:
      VITE_APP_ENV: ${VITE_APP_ENV}
      VITE_APP_BASE_API: ${VITE_APP_BASE_API}
      VITE_APP_TITLE: ${VITE_APP_TITLE}
    volumes:
      - .:/app
