# version: '3'
# services:
#   app:
#     build:
#       context: .
#       args:
#         NODE_ENV: staging
#     ports:
#       - '8081:80'
#     env_file:
#       - .env.staging

version: '3'
services:
  app:
    environment:
      - NODE_ENV=staging
      - VITE_APP_BASE_API_PRODUCTION=${VITE_APP_BASE_API_STAGING}
    ports:
      - '8084:80'
