version: '3'
services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
        - VITE_APP_BASE_API=${VITE_APP_BASE_API}
        - VITE_APP_ENV=${VITE_APP_ENV}
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
